### PR TITLE
Update bintray url and build snapweb

### PR DESCRIPTION
**Pull request by infeeeee**
- Bintray.com urls are not working anymore, so I replaced with another official source I found on boost's website
- Added commands to build snapweb as I mentioned in #2 

I only modified the main Dockerfile, and tested it. I didn't modify the other ones, as I don't know how to test them, but I guess everything should work on other platforms. 

This is the first time I write a dockerfile, so sorry if I made something wrong.

### CODE REVIEW

**Comment by Saiyato** [comment]
Hi,

I will check the building of snapweb, I want to minimize the number of directory jumps, I believe you can pass parameters to make to avoid having to jump into the directory.

I also found that boost had moved indeed, see the snapclient repo: https://github.com/Saiyato/snapclient_docker/blob/master/with-pulse/Dockerfile.arm32v7

I had to add the no-check-certificate though, let's see if this works without skipping the check today.

**Comment by infeeeee** [comment]
Removed directory jumps, `-C` option does exactly this.

Works for me without no-check-certificate, maybe they fixed it since?

Excerpt from the log:
```
Cloning into 'snapcast'...
Connecting to boostorg.jfrog.io (52.34.150.50:443)
Connecting to jfrog-prod-usw2-shared-oregon-main.s3.amazonaws.com (52.218.229.155:443)
saving to 'boost_1_75_0.tar.bz2'
boost_1_75_0.tar.bz2   0% |                                | 34233  0:59:37 ETA
```

**Comment by squat** [comment]
Hi @Saiyato is there anything holding up this PR?

**Comment by Saiyato** [comment]
Fair point, I don't think there's anything wrong with it. I've been busy working around the auto-build function being discontinued in Docker Hub, I actually need a machine that's going to be doing the building from now on :wink:

So I think we can safely merge the PR 👍

**Review by Saiyato — APPROVED** [review]
Seems legit

**Comment by squat** [comment]
> I've been busy working around the auto-build function being discontinued in Docker Hub, I actually need a machine that's going to be doing the building from now on

Can the builds be moved to GitHub Actions or some other CI rather than a machine you run personally?

**Comment by Saiyato** [comment]
Definitely, I'd rather not have a runner at home, but actions "only" give you so many minutes of automation time. But as said, looking into it, haven't decided on anything yet :wink: I had a nice thing going on with auto-builds, now I just need to move on

**Pull request merged**
